/* Main.c file generated by New Project wizard
 *
 * Created:   Mon May 16 2022
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

//#include <reg51.h>
#include <stdio.h>
#include <at89x51.h>

#define sbl(_sfr, bit) (_sfr |= (1 << bit))
#define cbl(_sfr, bit) (_sfr &= (~(1 << bit)))
#define tbl(_sfr, bit) (_sfr ^= (1 << bit))
#define red_time 10
#define yellow_time 3
#define start_phase 1

int mode = 1;
int ms = 0;
int second = red_time;
int phase = start_phase;
int red = 3;
int yellow = 2;
int green = 1;
void show_led_1(int time);
void show_led_2(int time);
void delay_10ms();
void delay(int time);
void phase_init();
void phase_update();
void phase_1();
void phase_2();
void phase_3();
void phase_4();
void phase_call();
void red_on(int x) 				{cbl(P3, x - 1);}
void yellow_on(int x) 		{cbl(P3, x + 3);}
void green_on(int x) 			{cbl(P3, x + 5);}
void red_off(int x) 			{sbl(P3, x - 1);}
void yellow_off(int x) 		{sbl(P3, x + 3);}
void green_off(int x) 		{sbl(P3, x + 5);}
void stop_on(int x)				{cbl(P0, 2 * x - 2);}
void walk_on(int x)				{cbl(P0, 2 * x - 1);}
void stop_off(int x)			{sbl(P0, 2 * x - 2);}
void walk_off(int x)			{sbl(P0, 2 * x - 1);}
void toggle_yellow(int x)	{tbl(P3, x + 3);}
void toggle_walk(int x)		{tbl(P0, 2 * x - 1);}
void phase_clear();
void mode_1();
void mode_2();

void main(void) 
   { 
      IE = 0x83;
      TMOD = 0x11;
			TCON = 0x01;
			TH0 = 0xFC;
      TL0 = 0x18;
			TR0 = 1;
			phase_init();
      while (1) {
					if (mode == 1) mode_1();
      }
   }

void INT0_ISR() interrupt 0 {
			if (mode == 1) {
					phase_clear();
					ms = 0;
					mode = 2;
			}
			else {
					yellow_off(1);
					yellow_off(2);
					ms = 0;
					second = red_time;
					phase = 1;
					mode = 1;
					phase_init();				
			}
}
	 
void Timer0_ISR() interrupt 1 
   {
      TR0 = 0;
      ms ++;
			if (mode == 1) {
					if (ms == 500 && second <= 6 && second >= 3) {
							if (phase == 1) walk_on(1);
							else if (phase == 3) walk_on(2);
					}
					if (ms == 1000) {
							ms = 0;
							second --;
							if (second <= 6 && second >= 3) {
								if (phase == 1) walk_off(1);
								else if (phase == 3) walk_off(2);
							}
					}
			}
			else {
					if (ms == 500) {
						toggle_yellow(1);
						toggle_yellow(2);
						ms = 0;
					}
			}
			TH0 = 0xFC;
      TL0 = 0x18;
      TR0 = 1;
   }
	 
void show_led_1(int time) 
   {
      int a = time / 10, b = time % 10;
      P1 = a;
      sbl(P1, 4);
      delay(10);
      cbl(P1, 4);
      P1 = b;
      sbl(P1, 5);
      delay(10);
      cbl(P1, 5);
   }

void show_led_2(int time) 
   {
      int a = time / 10, b = time % 10;
      P2 = a;
      sbl(P2, 4);
      delay(10);
      cbl(P2, 4);
      P2 = b;
      sbl(P2, 5);
      delay(10);
      cbl(P2, 5);
   }

void delay(int time) 
   {
      int i, n = time / 10;
      for (i = 0; i < n; ++ i) delay_10ms();
   }   

void delay_10ms() 
   {
      TH1 = 0xD8;
      TL1 = 0xF0;
      TR1 = 1;
      while (!TF1);
      TR1 = 0;
      TF1 = 0;
   }
	 
void phase_init() {
		if (phase == 1) {
				red_on(1);
				walk_on(1);
				green_on(2);
				stop_on(2);
		}
		else if (phase == 2) {
				red_on(1);
				stop_on(1);
				yellow_on(2);
				stop_on(2);
		}
		else if (phase == 3) {
				green_on(1);
				stop_on(1);	
				red_on(2);
				walk_on(2);
		}
		else {
				yellow_on(1);
				stop_on(1);
				red_on(2);
				stop_on(2);
		}	
}	

void phase_clear() {
		if (phase == 1) {
				red_off(1);
				walk_off(1);
				green_off(2);
				stop_off(2);
		}
		else if (phase == 2) {
				red_off(1);
				stop_off(1);
				yellow_off(2);
				stop_off(2);
		}
		else if (phase == 3) {
				green_off(1);
				stop_off(1);	
				red_off(2);
				walk_off(2);
		}
		else {
				yellow_off(1);
				stop_off(1);
				red_off(2);
				stop_off(2);
		}
}


void phase_update() {
			if (phase == 1) {
					if (second == yellow_time) {
						phase = 2;
						walk_off(1);
						stop_on(1);
						green_off(2);
						yellow_on(2);
					}
			}
			else if (phase == 2) {
					if (second == 0) {
						phase = 3;
						second = red_time;
						red_off(1);
						yellow_off(2);
						stop_off(2);
						green_on(1);
						red_on(2);
						walk_on(2);
					}
			}
			else if (phase == 3) {
					if (second == yellow_time) {
						phase = 4;
						green_off(1);
						yellow_on(1);
						walk_off(2);
						stop_on(2);
					}
			}
			else {
					if (second == 0) {
						phase = 1;
						second = red_time;
						yellow_off(1);
						stop_off(1);
						red_off(2);
						red_on(1);
						walk_on(1);
						green_on(2);
					}
			}
}

void phase_1() {
			show_led_1(second);
			show_led_2(second - yellow_time);
}

void phase_2() {
			show_led_1(second);
			show_led_2(second);
}

void phase_3() {
			show_led_1(second - yellow_time);
			show_led_2(second);
}

void phase_4() {
			show_led_1(second);
			show_led_2(second);
}

void phase_call() {
			if (phase == 1) phase_1();
			else if (phase == 2) phase_2();
			else if (phase == 3) phase_3();
			else phase_4();
}	 

void mode_1() {
			phase_update();
			phase_call();
}